<a href="https://colab.research.google.com/github/shashwat-sahuu/Dl_project_neural_network_using_pytorch.ipynb/blob/main/Dl_project_neural_network_using_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [60]:
# importing dependencies

In [61]:
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler


device configuration

In [62]:
#check for cuda avaialbility
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"using devce: {device}")

using devce: cuda


data collectionand preprocessing

In [63]:
# load the breast cancer dataset
data = load_breast_cancer()
X = data.data
Y = data.target

In [64]:
print(X)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]


In [65]:
print(Y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 0 1 1 1 1 0 0 0 1 1
 1 1 0 1 0 1 0 1 1 1 0 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 0 0 1 0 0
 0 1 0 0 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 0 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1
 1 0 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 0 1 0 1 1 1 1 1 0 1 1
 0 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1
 1 1 1 1 1 1 0 1 0 1 1 0 

In [66]:
print(Y[:5])

[0 0 0 0 0]


In [67]:
X_train, X_test, y_train, y_test = train_test_split(X, Y ,test_size=0.2, random_state=42)

In [68]:
print(X.shape)
print(X_train.shape)
print(X_test.shape)

(569, 30)
(455, 30)
(114, 30)


In [69]:
import numpy as np

#standardize the data using standard scaler
scaler = StandardScaler()

# Create copies to preserve original untransformed data if needed later
X_train_original = X_train.copy()
X_test_original = X_test.copy()

X_train = scaler.fit_transform(X_train_original)
X_test = scaler.transform(X_test_original)
type(X_train)

numpy.ndarray

In [70]:
X_train = torch.tensor(X_train, dtype=torch.float32).to(device)
y_train = torch.tensor(y_train, dtype=torch.float32).to(device)
X_test = torch.tensor(X_test, dtype=torch.float32).to(device)
y_test = torch.tensor(y_test, dtype=torch.float32).to(device)

neural network architecture


In [71]:
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

#define the neural network architecture
class NeuralNet(nn.Module):

  def __init__(self, input_size, hidden_size, output_size):
    super(NeuralNet, self).__init__()
    self.fc1 = nn.Linear(input_size, hidden_size)
    self.relu = nn.ReLU()
    self.fc2 = nn.Linear(hidden_size, output_size)
    self.sigmoid = nn.Sigmoid()

  def forward(self, X):
    out = self.fc1(X)
    out = self.relu(out)
    out = self.fc2(out)
    out = self.sigmoid(out)
    return out

In [72]:
#define hyperparameters
input_size = X_train.shape[1]
hidden_size = 64
output_size = 1
learning_rate = 0.001
num_epochs = 100


In [73]:
#intialize the neural network and move it the GPU
model = NeuralNet(input_size, hidden_size, output_size).to(device)

In [74]:
# define hyperparameters
input_size = X_train.shape[1]
hidden_size = 64
output_size = 1
learning_rate = 0.001
num_epochs = 100

In [75]:
# initialize the neural network and move it the GPU
model = NeuralNet(input_size, hidden_size, output_size).to(device)

In [76]:
# define loss and the optimizer
criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters(), lr=learning_rate)

training the model


In [77]:
# training the model
for epoch in range(num_epochs):
  model.train()
  optimizer.zero_grad()
  outputs = model(X_train)
  loss = criterion(outputs, y_train.view(-1,1))
  loss.backward()
  optimizer.step()
# calculae the accuracy
  with torch.no_grad():
    predicted = outputs.round()
    correct = (predicted == y_train.view(-1,1)).float().sum()
    accuracy = correct/y_train.size(0)

  if (epoch+1) % 10 == 0:
    print(f"Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}, Accuracy: {accuracy.item() * 100:.2f}%")

Epoch [10/100], Loss: 0.6058, Accuracy: 62.20%
Epoch [20/100], Loss: 0.4916, Accuracy: 90.33%
Epoch [30/100], Loss: 0.3965, Accuracy: 94.07%
Epoch [40/100], Loss: 0.3171, Accuracy: 95.16%
Epoch [50/100], Loss: 0.2545, Accuracy: 95.82%
Epoch [60/100], Loss: 0.2084, Accuracy: 96.04%
Epoch [70/100], Loss: 0.1753, Accuracy: 96.48%
Epoch [80/100], Loss: 0.1516, Accuracy: 97.14%
Epoch [90/100], Loss: 0.1340, Accuracy: 97.14%
Epoch [100/100], Loss: 0.1206, Accuracy: 97.36%


model evaluation


In [86]:
#evaluation on training set
model.eval()
with torch.no_grad():
  outputs = model(X_train)
  predicted = outputs.round()
  correct = (predicted == y_train.view(-1,1)).float().sum()
  accuracy = correct/y_train.size(0)
  print(f"Training Accuracy: {accuracy.item() * 100:.2f}%")

Training Accuracy: 97.36%


In [96]:
import torch
from sklearn.model_selection import train_test_split

# 1. Re-split to ensure we have the raw numpy arrays available
_, X_test_raw, _, y_test_raw = train_test_split(X, Y, test_size=0.2, random_state=42)

# 2. Scale the test data using the fitted scaler
X_test_scaled = scaler.transform(X_test_raw)

# 3. Convert to tensors and move to device
X_test_tensor = torch.tensor(X_test_scaled, dtype=torch.float32).to(device)
y_test_tensor = torch.tensor(y_test_raw, dtype=torch.float32).to(device)

# 4. Evaluate the model
model.eval()
with torch.no_grad():
    test_outputs = model(X_test_tensor)
    test_predicted = test_outputs.round()

    # Verify shapes
    print(f"X_test samples: {X_test_tensor.shape[0]}")
    print(f"y_test samples: {y_test_tensor.shape[0]}")

    # Calculate accuracy
    correct = (test_predicted == y_test_tensor.view(-1,1)).float().sum()
    test_accuracy = (correct / y_test_tensor.size(0)) * 100
    print(f"\nFinal Test Accuracy: {test_accuracy.item():.2f}%")

X_test samples: 114
y_test samples: 114

Final Test Accuracy: 97.37%


#